kind: pipeline
type: docker
name: Docker Build (main)

trigger:
  event:
  - cron
  - custom
  cron:
  - weekly

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

steps:
- name: Build and push release (main)
  image: fuzzymistborn/docker-alpine-skopeo:latest
  environment:
    DOCKERHUB_PASS:
      from_secret: dockerhub_pw
    GHCR_PASS:
      from_secret: ghcr_pw
    LMS_VER: 8.2
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker login docker.io -u fuzzymistborn -p $DOCKERHUB_PASS
    - docker login ghcr.io -u fuzzymistborn -p $GHCR_PASS
    - docker build -t fuzzymistborn/lms:latest -t fuzzymistborn/lms:$LMS_VER -t ghcr.io/fuzzymistborn/lms:latest -t ghcr.io/fuzzymistborn/lms:$LMS_VER .
    - docker push --all-tags fuzzymistborn/lms
    - docker push --all-tags ghcr.io/fuzzymistborn/lms

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "{{#success build.status}}✅  Build for `{{repo.name}}` was *successful*!{{else}}❌  Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
  when:
    status: [ success, failure ]

kind: pipeline
type: docker
name: Docker Build (dev)

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

steps:
- name: Build and push release (dev)
  image: fuzzymistborn/docker-alpine-skopeo:latest
  environment:
    DOCKERHUB_PASS:
      from_secret: dockerhub_pw
    GHCR_PASS:
      from_secret: ghcr_pw 
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker login docker.io -u fuzzymistborn -p $DOCKERHUB_PASS
    - docker login ghcr.io -u fuzzymistborn -p $GHCR_PASS
    - docker build -t fuzzymistborn/lms:dev -t ghcr.io/fuzzymistborn/lms:dev .
    - docker push fuzzymistborn/lms:dev
    - docker push ghcr.io/fuzzymistborn/lms:dev
  when:
    branch:
    - dev

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "{{#success build.status}}✅  Build for `{{repo.name}}` was *successful*!{{else}}❌  Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
  when:
    status: [ success, failure ]
    branch:
    - dev
